"""`runcomposer demo` — boots the neutral web-shop corpus end-to-end (DESIGN.md §12).

The whole loop, through the real machinery rather than a parallel in-process
imitation of it: manifest source → taxonomy view → tag-filter selection →
materialized runspec (validated against the shipped schema) → dispatch to the
`demo` runner → verdicts recorded in a store → a *history-derived* "rerun what
failed" selection resolved back out of that store, with provenance.

It seeds a real store to do it, because the run it demonstrates last —
"rerun what failed" — is precisely the one a fresh store cannot answer, and a
demo that narrates history it did not persist leaves the reader's very next
command contradicting the demo (§6.3, §12).

Where it writes is the other half of that promise, and it is deliberately
boring: a single directory, named for what it is, holding a `config.yaml` and
the sqlite file that config points at. Nothing outside it is touched — not the
adopter's own store, not a `runcomposer.db` in the working directory that a
later real run would then share with fake data. The directory is printed, it
is the `--config` of every next step the demo prints, and `rm -rf` on it is
the complete uninstall.
"""

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Any, Callable

import yaml

from runcomposer.config import load_config
from runcomposer.core.filter import format_filter, parse_filter
from runcomposer.core.model import Item, Verdict
from runcomposer.core.selection import Selection
from runcomposer.service import Service

_RULE = "─" * 64

Out = Callable[[str], Any]

DEFAULT_WORKSPACE = "runcomposer-demo"

#: First line of the generated config, and the demo's proof that a directory
#: is its own workspace rather than somebody's real deployment.
_MARKER = "# runcomposer demo workspace — generated by `runcomposer demo`."

_CONFIG = f"""{_MARKER}
# Throwaway: delete this directory and the demo is gone without a trace.
# Re-running `runcomposer demo` re-seeds the store from scratch.
#
# `path` is relative, and relative in a runcomposer config means "next to this
# file" (DESIGN.md §8) — so the commands the demo prints work from any
# directory, and the whole workspace can be moved or copied as one thing.
#
# No `sources:` and no `core.taxonomy_file:` on purpose: with neither
# configured, runcomposer falls back to the bundled demo corpus and taxonomy,
# which is exactly what seeded this store.
store:
  sqlite:
    path: runcomposer.db
"""


class DemoError(RuntimeError):
    """The demo cannot claim a workspace — reported, never worked around."""


# -- the workspace --------------------------------------------------------------


def _claim(target: Path) -> Path:
    """Create (or re-claim) a demo workspace at ``target``.

    Refuses anything that is not already one. `demo` writes files, so it gets
    to write them exactly where a reader can see it coming: a directory it
    created, or an empty one they named. A directory with a foreign
    `config.yaml` is somebody's deployment, and re-seeding it would delete
    their store.
    """
    config_file = target / "config.yaml"
    if config_file.exists():
        head = config_file.read_text(encoding="utf-8", errors="replace")[: len(_MARKER)]
        if head != _MARKER:
            raise DemoError(
                f"{config_file} exists and was not written by `runcomposer demo` — refusing to "
                "overwrite it or delete the store it points at. Pass --workspace DIR to seed "
                "the demo somewhere else."
            )
    elif target.exists() and any(target.iterdir()):
        raise DemoError(
            f"{target} is not empty and is not a demo workspace — refusing to seed into it. "
            "Pass --workspace DIR to name an empty or new directory."
        )
    target.mkdir(parents=True, exist_ok=True)
    config_file.write_text(_CONFIG, encoding="utf-8")
    store = target / "runcomposer.db"
    if store.exists():
        store.unlink()  # re-seed from scratch: the demo is deterministic
    return target


def _prepare_workspace(requested: str | None) -> tuple[Path, str]:
    """Return the workspace and a note about how it was chosen.

    A read-only working directory (a container, an installed package tree) is
    not a reason for the demo to fail — it falls back to a temp directory and
    says so, since the printed next steps carry the path either way.
    """
    target = Path(requested or DEFAULT_WORKSPACE)
    try:
        return _claim(target), ""
    except OSError as exc:
        if requested is not None:
            raise DemoError(f"cannot create the demo workspace {target}: {exc}") from None
        fallback = Path(tempfile.mkdtemp(prefix="runcomposer-demo-"))
        return _claim(fallback), f"(could not create ./{target}: {exc.strerror})"


# -- narration ------------------------------------------------------------------


def _print_taxonomy_node(node: dict, items: list[Item], out: Out, indent: int) -> None:
    pad = "  " * indent
    if "filter" in node:
        matcher = parse_filter(node["filter"])
        count = sum(1 for item in items if matcher.matches(item.tags))
        out(f"{pad}{node['label']:<12} {count:>3} items   ({node['filter']})")
    else:
        out(f"{pad}{node['label']}")
    for child in node.get("children", ()):
        _print_taxonomy_node(child, items, out, indent + 1)


def _summarize(verdicts: list[Verdict], out: Out) -> None:
    counts = {status: 0 for status in ("PASS", "FAIL", "SKIP", "ERROR")}
    for verdict in verdicts:
        counts[verdict.status] += 1
    total_s = sum(v.duration_ms for v in verdicts) / 1000
    parts = ", ".join(f"{n} {status}" for status, n in counts.items() if n)
    out(f"Results: {parts}  ({len(verdicts)} items, {total_s:.1f}s simulated)")
    failed = [v for v in verdicts if v.status == "FAIL"]
    for verdict in failed[:5]:
        out(f"  FAIL  {verdict.item_id} — {verdict.message}")
    if len(failed) > 5:
        out(f"  … and {len(failed) - 5} more failures")


def _compose_and_run(
    service: Service,
    *,
    title: str,
    seed: str,
    selection: dict[str, Any],
    labels: dict[str, str],
) -> tuple[dict, str, list[Verdict]]:
    """One full run through the service: compose (validated, stored), dispatch
    to the `demo` runner, then read the verdicts back **out of the store** —
    the summary the demo prints is what was persisted, not what was in hand.

    The per-run seed rides in the spec's one open section (`runner.demo.seed`,
    §3), which is what makes three nightly runs differ through one configured
    runner.
    """
    result = service.compose_run(
        selection,
        title=title,
        labels=labels,
        origin="demo",
        runner_section={"demo": {"seed": seed}},
    )
    assert result.run is not None
    dispatch = service.dispatch_runner(result.run.id, "demo")
    verdicts = service.store.verdicts_for(result.run.id, dispatch.dispatch_id)
    return result.spec, result.run.id, verdicts


def run_demo(out: Out = print, workspace: str | None = None) -> int:
    workspace_dir, note = _prepare_workspace(workspace)
    config_file = workspace_dir / "config.yaml"
    config_arg = str(config_file)
    service = Service(load_config(config_arg))
    items = service.source.items()

    out(_RULE)
    out("runcomposer demo — fictional web-shop corpus")
    out(_RULE)
    out(f"Corpus: {len(items)} items via the '{service.source.provider_id}' source")
    out(f"Catalog snapshot: {service.source.snapshot()[:29]}…")
    out(f"Workspace: {workspace_dir}{f'  {note}' if note else ''}")
    out("")

    out("Taxonomy (curated tree over tag patterns — data, not code):")
    taxonomy = yaml.safe_load(service.config.taxonomy_source.read_text(encoding="utf-8"))
    for node in taxonomy["taxonomy"]:
        _print_taxonomy_node(node, items, out, indent=1)
    out("")

    # 1) Compose: tag-filter selection → materialized, validated, stored runspec.
    filter_data = {
        "op": "AND",
        "items": [
            {"op": "OR", "items": ["Payments", "prefix:Checkout-", "regex:^Cart(V2)?$"]},
            {"not": "prefix:Quarantine-"},
        ],
    }
    matched = Selection.from_data({"tag_filter": filter_data}).compile(items)
    out(f"Selection: {format_filter(parse_filter(filter_data))}")
    out(f"  matched {len(matched)} of {len(items)} items")

    spec, run_id, verdicts = _compose_and_run(
        service,
        title="Web-shop regression without quarantined tests",
        seed="demo-1",
        selection={"tag_filter": filter_data},
        labels={"suite": "adhoc"},
    )
    out(f"Run spec {run_id}: validates against the runspec-1.0 schema (dispatch profile)")
    out("")
    out("Spec document (excerpt):")
    excerpt = yaml.safe_dump(spec, sort_keys=False, allow_unicode=True).splitlines()
    for line in excerpt[:14]:
        out(f"  {line}")
    out(f"  … ({len(excerpt) - 14} more lines)")
    out("")

    run = service.store.get_run(run_id)
    out(
        f"Dispatched to the 'demo' runner: dispatch {run.dispatches[-1].dispatch_id}, "
        f"{len(run.deliveries)} shard delivered — run {run.state} ({run.completion})"
    )
    _summarize(verdicts, out)
    out("")

    # 2) "Rerun what failed" — over history this command actually wrote (§7, §12).
    out(_RULE)
    out('"Rerun what failed" — history-derived selection')
    out(_RULE)
    regression = Selection.from_data({"tag_filter": "Regression"}).compile(items)
    nightly_ids = []
    for n in (1, 2, 3):
        _spec, nightly_id, _verdicts = _compose_and_run(
            service,
            title=f"Nightly regression #{n}",
            seed=f"nightly-{n}",
            selection={"tag_filter": "Regression"},
            labels={"suite": "nightly"},
        )
        nightly_ids.append(nightly_id)
    out(
        f"Seeded history: {len(nightly_ids)} completed runs over 'Regression' "
        f"({len(regression)} items each), persisted in {workspace_dir / 'runcomposer.db'}"
    )

    # The scope is the point (§7): "latest" unscoped is the latest completed
    # run of ANYTHING — including the ad-hoc one above, and, once the rerun
    # below completes, the rerun itself.
    failed_ids, provenance = service.resolve_history("failed@latest", labels={"suite": "nightly"})
    out(
        f"Latest completed 'suite=nightly' run {provenance['resolved_run_id']}: "
        f"{len(failed_ids)} FAIL"
    )
    if not failed_ids:
        out("Nothing failed in the latest nightly run — nothing to rerun.")
        return 0

    _spec, rerun_id, rerun_verdicts = _compose_and_run(
        service,
        title="Rerun failures of the latest nightly regression",
        seed="rerun-1",
        selection={"history": "failed@latest?suite=nightly"},
        labels={"suite": "adhoc"},
    )
    rerun_spec = service.store.get_spec_document(rerun_id)
    derived = rerun_spec["selection"]["derived_from"][0]
    out(
        f"Derived selection: {len(failed_ids)} items, provenance recorded in "
        f"selection.derived_from (run {derived['resolved_run_id']}, "
        f"scope {derived['query']['labels']})"
    )
    _summarize(rerun_verdicts, out)
    out("")

    stored = service.store.list_runs(limit=50)
    out(_RULE)
    out(
        f"Demo complete. {len(stored)} completed runs and "
        f"{sum(len(service.store.verdicts_for(r.id)) for r in stored)} verdicts are in "
        f"{workspace_dir / 'runcomposer.db'} — history features are live there."
    )
    out(f"Delete the workspace to undo all of it:  rm -rf {workspace_dir}")
    out("")
    out("Next steps:")
    out(f"  runcomposer runs --config {config_arg}")
    out(f"  runcomposer runs --config {config_arg} --failed-in latest --label suite=nightly")
    out(f"  runcomposer compile --config {config_arg} Payments")
    out(f"  runcomposer export {nightly_ids[-1]} --format ctrf --config {config_arg}")
    out(f"  runcomposer serve --config {config_arg}")
    return 0
